### ISSUE TITLE
Pipeline doesn't process all BAMs in input directory

### ISSUE THREAD

**Issue by kubu4** [EpiDiverse/snp#6]
Ran the following command to process 18 BAMs in the input directory:

```bash
NXF_VER=20.07.1 /home/shared/nextflow run epidiverse/snp \
-c nextflow-docker_permissions.config \
-profile docker \
--input /home/shared/8TB_HDD_01/sam/data/O_lurida/BSseq/bams/070322-olymerge-snp/ \
--reference /home/shared/8TB_HDD_01/sam/data/O_lurida/genomes/Olurida_v081-mergecat98.fa
```

For some reason, the pipeline only processed 10 of the 18 and the selection of which files were selected seems random. For example, here is the list of files processed:

```
zr1394_3_s456_trimmed_bismark_bt2.deduplicated.bam
zr1394_6_s456_trimmed_bismark_bt2.deduplicated.bam
zr1394_7_s456_trimmed_bismark_bt2.deduplicated.bam
zr1394_8_s456_trimmed_bismark_bt2.deduplicated.bam
zr1394_9_s456_trimmed_bismark_bt2.deduplicated.bam
zr1394_10_s456_trimmed_bismark_bt2.deduplicated.bam
zr1394_11_s456_trimmed_bismark_bt2.deduplicated.bam
zr1394_15_s456_trimmed_bismark_bt2.deduplicated.bam
zr1394_16_s456_trimmed_bismark_bt2.deduplicated.bam
zr1394_18_s456_trimmed_bismark_bt2.deduplicated.bam 
```

These were numbered sequentially (`zr1394_{1..18}_s456_trimmed_bismark_bt2.deduplicated.bam`).

Any idea on what might be happening here and/or where I can look in the logs to see why some were analyzed while others were skipped?

**Comment by bio15anu** [comment]
Hi there, thanks for opening these issues for the various pipelines in the Epidiverse toolkit! It's always good to hear from people, particularly outside the network, who are using the pipelines. Just FYI- I am currently out on vacation, but expect to be back next week and will do my best to get to all your open tickets as soon as possible.

In regards to this issue specifically, I think it's probably due to the `--take` parameter which may be undocumented in this pipeline. The idea is to not inadvertently fill up all the available disk space on the system by creating huge work directories, so by default it is limited to 10 samples (I think). You can increase the number of samples with this parameter if you have plenty of space available and expect your system can handle it.

**Comment by kubu4** [comment]
Thanks again for the help. Using the `--take <INTEGER>` parameter was they key!
