### ISSUE TITLE
Output(s) don't match documentation

### ISSUE THREAD

**Issue by kubu4** [EpiDiverse/snp#7]
I've run the pipeline, but a couple of my outputs aren't matching [what's shown in the documentation](https://github.com/EpiDiverse/snp/blob/master/docs/output.md).

In `snps/bam/clusters`, the documentation indicates there should be BAM files. Instead, there are gzipped FastQ files.

In `snps/vcf`, the documentation indicates there should be gzipped VCF files (`*.vcf.gz`), but I only get regular VCF file (i.e. `*.vcf`).

**Comment by bio15anu** [comment]
Thanks for picking up on this detail. As of [2955915](https://github.com/EpiDiverse/snp/commit/2955915791eadfb888b72bbcd6df8b01323a650d) I've now altered the handling of intermediary files somewhat, and updated the documentation to reflect this.

By default, masked bam files for variant calling are only now produced if the user runs the pipeline in default mode (i.e. without specifying `--variants` or `--clusters`, as per the feature request in issue #5). Should you otherwise wish to get the intermediary (masked) bam or fastq files during variant calling and/or clustering, you can now make use of `--keepBams` or `--keepReads` to get them in the output directory.

These intermediary files take up a lot of disk space and so hopefully this will avoid cluttering up the system with large work directories and so on.
